apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["51.77.136.161"],"port":30290,"protocol":"TCP","serviceName":"prometheus:prometheus-alertmanager","allNodes":true}]'
  labels:
    app: prometheus
    chart: prometheus-6.2.1
    component: alertmanager
    heritage: Tiller
    io.cattle.field/appId: prometheus
    release: prometheus
  name: prometheus-alertmanager
  namespace: prometheus
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30290
    port: 80
    protocol: TCP
    targetPort: 9093
  selector:
    app: prometheus
    component: alertmanager
    release: prometheus
  sessionAffinity: None
  type: NodePort
