apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["51.77.136.161"],"port":30828,"protocol":"TCP","serviceName":"prometheus:prometheus-server","allNodes":true}]'
  labels:
    app: prometheus
    chart: prometheus-6.2.1
    component: server
    heritage: Tiller
    io.cattle.field/appId: prometheus
    release: prometheus
  name: prometheus-server
  namespace: prometheus
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30828
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
    component: server
    release: prometheus
  sessionAffinity: None
  type: NodePort
