apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["51.77.136.161"],"port":31508,"protocol":"TCP","serviceName":"efk:efk-elasticsearch","allNodes":true},{"addresses":["51.77.136.161"],"port":30637,"protocol":"TCP","serviceName":"efk:efk-elasticsearch","allNodes":true}]'
  labels:
    app: elasticsearch
    chart: elasticsearch-0.1.0
    heritage: Tiller
    io.cattle.field/appId: efk
    release: efk
  name: efk-elasticsearch
  namespace: efk
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 31508
    port: 9200
    protocol: TCP
    targetPort: http
  - name: transport
    nodePort: 30637
    port: 9300
    protocol: TCP
    targetPort: transport
  selector:
    app: elasticsearch
    component: master
    release: efk
  sessionAffinity: None
  type: NodePort
