apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: mongodb-replicaset
    release: mongodb-replicaset
  name: datadir-mongodb-replicaset-2
  namespace: mongodb-replicaset
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: local-storage
  volumeName: mongo-one
