apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-replicaset
    chart: mongodb-replicaset-3.9.2
    heritage: Tiller
    io.cattle.field/appId: mongodb-replicaset
    release: mongodb-replicaset
  name: mongodb-replicaset-client
  namespace: mongodb-replicaset
spec:
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb-replicaset
    release: mongodb-replicaset
  sessionAffinity: None
  type: ClusterIP
