apiVersion: v1
data:
  mongod.conf: '{}

    '
kind: ConfigMap
metadata:
  labels:
    app: mongodb-replicaset
    chart: mongodb-replicaset-3.9.2
    heritage: Tiller
    io.cattle.field/appId: mongodb-replicaset
    release: mongodb-replicaset
  name: mongodb-replicaset-mongodb
  namespace: mongodb-replicaset
