apiVersion: v1
data:
  DEBUG: api:*
  NODE_ENV: production
kind: ConfigMap
metadata:
  annotations:
    field.cattle.io/creatorId: user-5dn6d
  labels:
    cattle.io/creator: norman
  name: api
  namespace: draw
