apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/creatorId: user-5dn6d
    field.cattle.io/ingressState: '{"ZHJhdy9kcmF3L2RyYXcuYmx1ZWZvcmVzdC5vcmcvL2FwaS84MA==":"daemonset:draw:film","ZHJhdy9kcmF3L2RyYXcuYmx1ZWZvcmVzdC5vcmcvLy84MA==":"daemonset:draw:draw"}'
    field.cattle.io/publicEndpoints: '[{"addresses":["51.77.137.98"],"port":80,"protocol":"HTTP","serviceName":"draw:ingress-4b7348b346164f86a0032da148adf0c1","ingressName":"draw:draw","hostname":"draw.blueforest.org","path":"/api","allNodes":true},{"addresses":["51.77.137.98"],"port":80,"protocol":"HTTP","serviceName":"draw:ingress-5091412d0b33a593c4061f313623113f","ingressName":"draw:draw","hostname":"draw.blueforest.org","path":"/","allNodes":true}]'
  labels:
    cattle.io/creator: norman
  name: draw
  namespace: draw
spec:
  rules:
  - host: draw.blueforest.org
    http:
      paths:
      - backend:
          serviceName: ingress-5091412d0b33a593c4061f313623113f
          servicePort: 80
        path: /
      - backend:
          serviceName: ingress-4b7348b346164f86a0032da148adf0c1
          servicePort: 80
        path: /api
