apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    field.cattle.io/creatorId: user-5dn6d
    field.cattle.io/publicEndpoints: '[{"addresses":["51.77.136.161"],"port":443,"protocol":"HTTPS","serviceName":"draw:ingress-c4175be79c7b11999d48c344c8c7ee28","ingressName":"draw:draw","hostname":"draw.blueforest.org","path":"/api/film","allNodes":true}]'
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: daemonSet-draw-film
  name: film
  namespace: draw
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: daemonSet-draw-film
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2019-03-06T13:53:56Z'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: daemonSet-draw-film
    spec:
      containers:
      - env:
        - name: PORT
          value: '80'
        envFrom:
        - secretRef:
            name: mongo
            optional: false
        - configMapRef:
            name: api
            optional: false
        image: blueforest/film:2.0.1
        imagePullPolicy: Always
        name: film
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: hub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  templateGeneration: 4
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
