apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
    chart: postgresql-5.2.1
    heritage: Tiller
    io.cattle.field/appId: postgresql-rtpct
    release: postgresql-rtpct
  name: postgresql-rtpct-postgresql-headless
  namespace: postgresql-rtpct
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: postgresql
  selector:
    app: postgresql
    release: postgresql-rtpct
  sessionAffinity: None
  type: ClusterIP
