apiVersion: v1
data:
  cluster-state: "nodes:\n- nodeName: c-5qdp4:m-35d6d33467aa\n  address: 51.77.137.108\n\
    \  port: \"22\"\n  internal_address: 51.77.137.108\n  role:\n  - etcd\n  - controlplane\n\
    \  - worker\n  hostname_override: three\n  user: root\n  docker_socket: \"\"\n\
    \  ssh_key: \"\"\n  ssh_key_path: ~/.ssh/id_rsa\n  labels: {}\n- nodeName: c-5qdp4:m-b8a9f715dbb6\n\
    \  address: 51.77.137.98\n  port: \"22\"\n  internal_address: 51.77.137.98\n \
    \ role:\n  - etcd\n  - controlplane\n  - worker\n  hostname_override: two\n  user:\
    \ root\n  docker_socket: \"\"\n  ssh_key: \"\"\n  ssh_key_path: ~/.ssh/id_rsa\n\
    \  labels: {}\n- nodeName: c-5qdp4:m-f97c5d29941b\n  address: 51.77.136.161\n\
    \  port: \"22\"\n  internal_address: 51.77.136.161\n  role:\n  - etcd\n  - controlplane\n\
    \  - worker\n  hostname_override: one\n  user: root\n  docker_socket: \"\"\n \
    \ ssh_key: \"\"\n  ssh_key_path: ~/.ssh/id_rsa\n  labels: {}\nservices:\n  etcd:\n\
    \    image: rancher/coreos-etcd:v3.2.18\n    extra_args:\n      election-timeout:\
    \ \"5000\"\n      heartbeat-interval: \"500\"\n    extra_binds: []\n    extra_env:\
    \ []\n    external_urls: []\n    ca_cert: \"\"\n    cert: \"\"\n    key: \"\"\n\
    \    path: \"\"\n    snapshot: true\n    retention: 72h\n    creation: 12h\n \
    \ kube-api:\n    image: rancher/hyperkube:v1.11.5-rancher1\n    extra_args: {}\n\
    \    extra_binds: []\n    extra_env: []\n    service_cluster_ip_range: 10.43.0.0/16\n\
    \    service_node_port_range: 30000-32767\n    pod_security_policy: false\n  kube-controller:\n\
    \    image: rancher/hyperkube:v1.11.5-rancher1\n    extra_args: {}\n    extra_binds:\
    \ []\n    extra_env: []\n    cluster_cidr: 10.42.0.0/16\n    service_cluster_ip_range:\
    \ 10.43.0.0/16\n  scheduler:\n    image: rancher/hyperkube:v1.11.5-rancher1\n\
    \    extra_args: {}\n    extra_binds: []\n    extra_env: []\n  kubelet:\n    image:\
    \ rancher/hyperkube:v1.11.5-rancher1\n    extra_args: {}\n    extra_binds:\n \
    \   - /mongo:/mongo:rshared\n    extra_env: []\n    cluster_domain: cluster.local\n\
    \    infra_container_image: rancher/pause-amd64:3.1\n    cluster_dns_server: 10.43.0.10\n\
    \    fail_swap_on: false\n  kubeproxy:\n    image: rancher/hyperkube:v1.11.5-rancher1\n\
    \    extra_args: {}\n    extra_binds: []\n    extra_env: []\nnetwork:\n  plugin:\
    \ canal\n  options:\n    canal_flannel_backend_type: vxlan\n    flannelBackendType:\
    \ vxlan\nauthentication:\n  strategy: x509\n  options: {}\n  sans: []\naddons:\
    \ \"\"\naddons_include: []\nsystem_images:\n  etcd: rancher/coreos-etcd:v3.2.18\n\
    \  alpine: rancher/rke-tools:v0.1.15\n  nginx_proxy: rancher/rke-tools:v0.1.15\n\
    \  cert_downloader: rancher/rke-tools:v0.1.15\n  kubernetes_services_sidecar:\
    \ rancher/rke-tools:v0.1.15\n  kubedns: rancher/k8s-dns-kube-dns-amd64:1.14.10\n\
    \  dnsmasq: rancher/k8s-dns-dnsmasq-nanny-amd64:1.14.10\n  kubedns_sidecar: rancher/k8s-dns-sidecar-amd64:1.14.10\n\
    \  kubedns_autoscaler: rancher/cluster-proportional-autoscaler-amd64:1.0.0\n \
    \ kubernetes: rancher/hyperkube:v1.11.5-rancher1\n  flannel: rancher/coreos-flannel:v0.10.0\n\
    \  flannel_cni: rancher/coreos-flannel-cni:v0.3.0\n  calico_node: rancher/calico-node:v3.1.3\n\
    \  calico_cni: rancher/calico-cni:v3.1.3\n  calico_controllers: \"\"\n  calico_ctl:\
    \ rancher/calico-ctl:v2.0.0\n  canal_node: rancher/calico-node:v3.1.3\n  canal_cni:\
    \ rancher/calico-cni:v3.1.3\n  canal_flannel: rancher/coreos-flannel:v0.10.0\n\
    \  wave_node: weaveworks/weave-kube:2.1.2\n  weave_cni: weaveworks/weave-npc:2.1.2\n\
    \  pod_infra_container: rancher/pause-amd64:3.1\n  ingress: rancher/nginx-ingress-controller:0.16.2-rancher1\n\
    \  ingress_backend: rancher/nginx-ingress-controller-defaultbackend:1.4\n  metrics_server:\
    \ rancher/metrics-server-amd64:v0.2.1\nssh_key_path: ~/.ssh/id_rsa\nssh_agent_auth:\
    \ false\nauthorization:\n  mode: rbac\n  options: {}\nignore_docker_version: true\n\
    kubernetes_version: v1.11.5-rancher1-1\nprivate_registries: []\ningress:\n  provider:\
    \ nginx\n  options: {}\n  node_selector: {}\n  extra_args: {}\ncluster_name: local\n\
    cloud_provider:\n  name: \"\"\nprefix_path: /\naddon_job_timeout: 30\nbastion_host:\n\
    \  address: \"\"\n  port: \"\"\n  user: \"\"\n  ssh_key: \"\"\n  ssh_key_path:\
    \ \"\"\nmonitoring:\n  provider: metrics-server\n  options: {}\n"
kind: ConfigMap
metadata:
  name: cluster-state
  namespace: kube-system
