apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    kubernetes.io/name: Metrics-server
  name: metrics-server
  namespace: kube-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    k8s-app: metrics-server
  sessionAffinity: None
  type: ClusterIP
