apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    field.cattle.io/creatorId: user-5dn6d
    field.cattle.io/publicEndpoints: '[{"addresses":["51.77.136.161"],"port":443,"protocol":"HTTPS","serviceName":"bf:ingress-bf451107538ad5970aaae58c4af70762","ingressName":"bf:drawhand","hostname":"draw.blueforest.org","path":"/api","allNodes":true},{"addresses":["51.77.136.161"],"port":443,"protocol":"HTTPS","serviceName":"bf:ingress-ee204bf032e5a331b13a5e7eb54261e7","ingressName":"bf:bf-ing","hostname":"blueforest.org","path":"/api","allNodes":true}]'
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: daemonSet-bf-bf-gateway
  name: bf-gateway
  namespace: bf
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: daemonSet-bf-bf-gateway
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2019-05-13T08:27:31Z'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: daemonSet-bf-bf-gateway
    spec:
      containers:
      - env:
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              key: DEBUG
              name: log
              optional: false
        envFrom:
        - secretRef:
            name: jwt
            optional: false
        image: blueforest/gateway:1.0.5
        imagePullPolicy: Always
        name: bf-gateway
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: usr/local/openresty/nginx/conf
          name: conf
          readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: hub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: nginx.conf
            path: nginx.conf
          name: gateway
          optional: false
        name: conf
  templateGeneration: 2
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
