apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    field.cattle.io/creatorId: user-5dn6d
    field.cattle.io/ingressState: '{"YmYtaW5nL2JmL2JsdWVmb3Jlc3Qub3JnLy8vODA=":"daemonset:bf:bf-web","YmYtaW5nL2JmL2JsdWVmb3Jlc3Qub3JnLy9hcGkvODA=":"daemonset:bf:bf-gateway","ZmV6OTQ4":"bf:fez948"}'
    field.cattle.io/publicEndpoints: '[{"addresses":["51.77.136.161"],"port":443,"protocol":"HTTPS","serviceName":"bf:ingress-a08f5f00fc38a36b135f10009d58e0fc","ingressName":"bf:bf-ing","hostname":"blueforest.org","path":"/","allNodes":true},{"addresses":["51.77.136.161"],"port":443,"protocol":"HTTPS","serviceName":"bf:ingress-ee204bf032e5a331b13a5e7eb54261e7","ingressName":"bf:bf-ing","hostname":"blueforest.org","path":"/api","allNodes":true}]'
    kubernetes.io/tls-acme: '"true"'
  labels:
    cattle.io/creator: norman
  name: bf-ing
  namespace: bf
spec:
  rules:
  - host: blueforest.org
    http:
      paths:
      - backend:
          serviceName: ingress-ee204bf032e5a331b13a5e7eb54261e7
          servicePort: 80
        path: /api
      - backend:
          serviceName: ingress-a08f5f00fc38a36b135f10009d58e0fc
          servicePort: 80
        path: /
  tls:
  - hosts:
    - blueforest.org
    secretName: fez948
