apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    field.cattle.io/creatorId: user-5dn6d
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: daemonSet-bf-bf-selection
  name: bf-selection
  namespace: bf
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: daemonSet-bf-bf-selection
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2019-05-13T08:23:14Z'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: daemonSet-bf-bf-selection
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: mongo
            optional: false
        - configMapRef:
            name: bf
            optional: false
        - configMapRef:
            name: log
            optional: false
        image: blueforest/selection:0.0.4
        imagePullPolicy: Always
        name: bf-selection
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: hub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  templateGeneration: 1
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
