apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    field.cattle.io/creatorId: user-5dn6d
    field.cattle.io/ingressState: '{"ZHJhd2hhbmQvYmYvZHJhdy5ibHVlZm9yZXN0Lm9yZy8vLzgw":"daemonset:bf:bf-draw","ZHJhd2hhbmQvYmYvZHJhdy5ibHVlZm9yZXN0Lm9yZy8vYXBpLzgw":"daemonset:bf:bf-gateway","eW95bw==":"bf:yoyo"}'
    field.cattle.io/publicEndpoints: '[{"addresses":["\u003cnil\u003e"],"port":443,"protocol":"HTTPS","serviceName":"bf:ingress-df9370f970ddaf7e39c874ed341a96bb","ingressName":"bf:drawhand","hostname":"draw.blueforest.org","path":"/","allNodes":true},{"addresses":["\u003cnil\u003e"],"port":443,"protocol":"HTTPS","serviceName":"bf:ingress-bf451107538ad5970aaae58c4af70762","ingressName":"bf:drawhand","hostname":"draw.blueforest.org","path":"/api","allNodes":true}]'
    kubernetes.io/tls-acme: '"true"'
  labels:
    cattle.io/creator: norman
  name: drawhand
  namespace: bf
spec:
  rules:
  - host: draw.blueforest.org
    http:
      paths:
      - backend:
          serviceName: ingress-df9370f970ddaf7e39c874ed341a96bb
          servicePort: 80
        path: /
      - backend:
          serviceName: ingress-bf451107538ad5970aaae58c4af70762
          servicePort: 80
        path: /api
  tls:
  - hosts:
    - draw.blueforest.org
    secretName: yoyo
