apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    field.cattle.io/creatorId: user-5dn6d
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: daemonSet-bf-game
  name: game
  namespace: bf
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: daemonSet-bf-game
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2019-04-11T15:45:33Z'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: daemonSet-bf-game
    spec:
      containers:
      - env:
        - name: DB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              key: DB_CONNECTION_STRING
              name: mongo
              optional: false
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              key: NODE_ENV
              name: bf
              optional: false
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              key: DEBUG
              name: log
              optional: false
        image: blueforest/game:0.0.5
        imagePullPolicy: Always
        name: game
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /mq.json
          name: rabbit
          subPath: mq.json
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: hub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: rabbit
        secret:
          defaultMode: 256
          optional: false
          secretName: rabbit
  templateGeneration: 8
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
