apiVersion: v1
data:
  nginx.conf: "env JWT_SECRET;\n\nworker_processes  1;\n\nevents {\n    worker_connections\
    \  1024;\n}\n\nhttp {\n    log_format correlationId '$remote_addr - $remote_user\
    \ [$time_local] '\n        '\"$request\" $status $body_bytes_sent '\n        '\"\
    $http_referer\" \"$http_user_agent\" \"$http_x_correlation_id\"';\n\n\n    lua_package_path\
    \ \"/usr/local/openresty/nginx/bf/lua/?.lua;;\";\n    include       ../bf/mime.types;\n\
    \    default_type  application/octet-stream;\n\n    sendfile        on;\n    keepalive_timeout\
    \  65;\n    gzip  on;\n\n    server {\n        listen 80;\n        listen [::]:80;\n\
    \        root /var/www;\n        index index.html;\n        location /api/user\
    \ {\n            proxy_pass http://user;\n        }\n        location /api/categorie\
    \ {\n            access_by_lua_block {\n                local gt = require \"\
    gateway\"\n                gt:verifyToken({\"^P\",\"^D\"})\n            }\n  \
    \          proxy_pass http://categorie;\n        }\n        location /api/grandeur\
    \ {\n            proxy_pass http://grandeur;\n        }\n        location /api/tree\
    \ {\n            access_by_lua_block {\n                local gt = require \"\
    gateway\"\n                gt:verifyToken({\"^P\",\"^D\"})\n            }\n  \
    \          proxy_pass http://tree;\n        }\n        location /api/facet {\n\
    \            access_by_lua_block {\n                local gt = require \"gateway\"\
    \n                gt:verifyToken({\"^P\",\"^D\"})\n            }\n           \
    \ proxy_pass http://facet;\n        }\n        location /api/message {\n     \
    \       access_by_lua_block {\n                local gt = require \"gateway\"\n\
    \                gt:verifyToken({\"^P\",\"^D\"})\n            }\n            proxy_pass\
    \ http://message;\n        }\n        location /api/damage {\n            access_by_lua_block\
    \ {\n                local gt = require \"gateway\"\n                gt:verifyToken({\"\
    ^P\",\"^D\"})\n            }\n            proxy_pass http://damage;\n        }\n\
    \        location /api/impact {\n            access_by_lua_block {\n         \
    \       local gt = require \"gateway\"\n                gt:verifyToken({\"^P\"\
    ,\"^D\"})\n            }\n            proxy_pass http://impact;\n        }\n \
    \       location /api/selection {\n            access_by_lua_block {\n       \
    \         local gt = require \"gateway\"\n                gt:verifyToken({\"^P\"\
    ,\"^D\"})\n            }\n            proxy_pass http://selection;\n        }\n\
    \        location /api/info {\n            access_by_lua_block {\n           \
    \     local gt = require \"gateway\"\n                gt:verifyToken({\"^P\",\"\
    ^D\"})\n            }\n            proxy_pass http://info;\n        }\n    }\n\
    }"
kind: ConfigMap
metadata:
  annotations:
    field.cattle.io/creatorId: user-5dn6d
  labels:
    cattle.io/creator: norman
  name: gateway
  namespace: bf
