apiVersion: v1
data:
  nginx.conf: "env JWT_SECRET;\n\nworker_processes  1;\n\nevents {\n    worker_connections\
    \  1024;\n}\n\nhttp {\n    log_format json '{\"request_id\": \"$sent_http_request_id\"\
    , \"method\": \"$request_method\", \"status\":$status, \"vhost\": \"$host\", \"\
    path\": \"$uri\",\"request_query\": \"$args\", \"request_length\": $request_length,\
    \ \"duration\": $request_time, \"bytes_sent\": $bytes_sent, \"request_proto\"\
    : \"$server_protocol\", \"http_user_agent\":\"$http_user_agent\" }';\n\n\n   \
    \ lua_package_path \"/usr/local/openresty/nginx/bf/lua/?.lua;;\";\n    include\
    \       ../bf/mime.types;\n    default_type  application/octet-stream;\n\n   \
    \ sendfile        on;\n    keepalive_timeout  65;\n    gzip  on;\n\n    server\
    \ {\n\t\taccess_log logs/access.log json;\n        listen 80;\n        listen\
    \ [::]:80;\n        root /var/www;\n        index index.html;\n        location\
    \ /api/user {\n            proxy_pass http://user;\n        }\n        location\
    \ /api/categorie {\n            access_by_lua_block {\n                local gt\
    \ = require \"gateway\"\n                gt:verifyToken({\"^P\",\"^D\"})\n   \
    \         }\n            proxy_pass http://categorie;\n        }\n        location\
    \ /api/grandeur {\n            proxy_pass http://grandeur;\n        }\n      \
    \  location /api/tree {\n            access_by_lua_block {\n                local\
    \ gt = require \"gateway\"\n                gt:verifyToken({\"^P\",\"^D\"})\n\
    \            }\n            proxy_pass http://tree;\n        }\n        location\
    \ /api/facet {\n            access_by_lua_block {\n                local gt =\
    \ require \"gateway\"\n                gt:verifyToken({\"^P\",\"^D\"})\n     \
    \       }\n            proxy_pass http://facet;\n        }\n        location /api/message\
    \ {\n            access_by_lua_block {\n                local gt = require \"\
    gateway\"\n                gt:verifyToken({\"^P\",\"^D\"})\n            }\n  \
    \          proxy_pass http://message;\n        }\n        location /api/impact\
    \ {\n            access_by_lua_block {\n                local gt = require \"\
    gateway\"\n                gt:verifyToken({\"^P\",\"^D\"})\n            }\n  \
    \          proxy_pass http://impact;\n        }\n        location /api/selection\
    \ {\n            access_by_lua_block {\n                local gt = require \"\
    gateway\"\n                gt:verifyToken({\"^P\",\"^D\"})\n            }\n  \
    \          proxy_pass http://selection;\n        }\n        location /api/info\
    \ {\n            access_by_lua_block {\n                local gt = require \"\
    gateway\"\n                gt:verifyToken({\"^P\",\"^D\"})\n            }\n  \
    \          proxy_pass http://info;\n        }\n        location /api/game {\n\
    \            access_by_lua_block {\n                local gt = require \"gateway\"\
    \n                gt:verifyToken({\"^P\",\"^D\"})\n            }\n           \
    \ proxy_pass http://game;\n        }\n\t\tlocation /api/film {\n            access_by_lua_block\
    \ {\n                local gt = require \"gateway\"\n                gt:verifyToken({\"\
    ^P\",\"^D\"})\n            }\n            proxy_pass http://film;\n        }\n\
    \    }\n}"
kind: ConfigMap
metadata:
  annotations:
    field.cattle.io/creatorId: user-5dn6d
  labels:
    cattle.io/creator: norman
  name: gateway
  namespace: bf
