apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    field.cattle.io/creatorId: user-5dn6d
    field.cattle.io/publicEndpoints: '[{"addresses":["51.77.136.161"],"port":443,"protocol":"HTTPS","serviceName":"bf:ingress-06d812feeaab9b03f4822034aad73860","ingressName":"bf:bf-ing","hostname":"integ.blueforest.org","path":"/api","allNodes":true}]'
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: daemonSet-bf-gateway
  name: gateway
  namespace: bf
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: daemonSet-bf-gateway
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2019-02-12T09:39:45Z'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: daemonSet-bf-gateway
    spec:
      containers:
      - env:
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              key: DEBUG
              name: log
              optional: false
        envFrom:
        - secretRef:
            name: jwt
            optional: false
        image: blueforest/gateway:1.0.5
        imagePullPolicy: Always
        name: gateway
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: nginx.conf
          name: conf
          readOnly: true
          subPath: usr/local/openresty/nginx/conf
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: hub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 256
          name: gateway
          optional: false
        name: conf
  templateGeneration: 22
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
