apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    field.cattle.io/creatorId: user-5dn6d
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: daemonSet-bf-grandeur
  name: grandeur
  namespace: bf
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: daemonSet-bf-grandeur
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2018-12-08T17:32:29Z'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: daemonSet-bf-grandeur
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: bf
            optional: false
        image: blueforest/grandeur:1.0.10
        imagePullPolicy: Always
        name: grandeur
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  templateGeneration: 1
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
