apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '7'
    field.cattle.io/creatorId: user-5dn6d
    field.cattle.io/publicEndpoints: '[{"addresses":["51.77.136.161"],"port":443,"protocol":"HTTPS","serviceName":"bf:ingress-6e2f672d4ca2e7b2ab11ed03bcda91da","ingressName":"bf:imf","hostname":"imf.blueforest.org","allNodes":true}]'
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-bf-imf
  name: imf
  namespace: bf
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-bf-imf
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2019-06-14T14:36:42Z'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-bf-imf
    spec:
      containers:
      - env:
        - name: DB_NAME
          value: postgres
        - name: DB_PWD
          value: m74KJzvUU3
        - name: DB_URL
          value: jdbc:postgresql://postgresql-rtpct-postgresql.postgresql-rtpct.svc.cluster.local:5432/spies
        image: blueforest/imf:9
        imagePullPolicy: Always
        name: imf
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: hub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
