apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["daemonset:bf:bf-draw"]'
  labels:
    cattle.io/creator: norman
  name: ingress-df9370f970ddaf7e39c874ed341a96bb
  namespace: bf
  ownerReferences:
  - apiVersion: v1beta1/extensions
    controller: true
    kind: Ingress
    name: drawhand
    uid: 4549aa1a-515c-11e9-b6ba-fa163e4f813e
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workloadID_ingress-df9370f970ddaf7e39c874ed341a96bb: 'true'
  sessionAffinity: None
  type: ClusterIP
