apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["daemonset:bf:gateway"]'
  labels:
    cattle.io/creator: norman
  name: ingress-bff4d17b5cd480135511fd99e58b83ae
  namespace: bf
  ownerReferences:
  - apiVersion: v1beta1/extensions
    controller: true
    kind: Ingress
    name: drawhand
    uid: 4549aa1a-515c-11e9-b6ba-fa163e4f813e
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workloadID_ingress-bff4d17b5cd480135511fd99e58b83ae: 'true'
  sessionAffinity: None
  type: ClusterIP
