apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["daemonset:bf:gateway"]'
  labels:
    cattle.io/creator: norman
  name: ingress-c1d538ee0a3fbfbd7932d0b44f0fc456
  namespace: bf
  ownerReferences:
  - apiVersion: v1beta1/extensions
    controller: true
    kind: Ingress
    name: draw
    uid: 634e98eb-50b1-11e9-b6ba-fa163e4f813e
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workloadID_ingress-c1d538ee0a3fbfbd7932d0b44f0fc456: 'true'
  sessionAffinity: None
  type: ClusterIP
