apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["daemonset:bf:gateway"]'
  labels:
    cattle.io/creator: norman
  name: ingress-ee204bf032e5a331b13a5e7eb54261e7
  namespace: bf
  ownerReferences:
  - apiVersion: v1beta1/extensions
    controller: true
    kind: Ingress
    name: bf-ing
    uid: 796ba2a5-fe1f-11e8-8468-fa163e4f813e
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workloadID_ingress-ee204bf032e5a331b13a5e7eb54261e7: 'true'
  sessionAffinity: None
  type: ClusterIP
