apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["daemonset:bf:draw"]'
  labels:
    cattle.io/creator: norman
  name: ingress-a4a75b7a78c0486724470009e323aa63
  namespace: bf
  ownerReferences:
  - apiVersion: v1beta1/extensions
    controller: true
    kind: Ingress
    name: drawhand
    uid: 4549aa1a-515c-11e9-b6ba-fa163e4f813e
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workloadID_ingress-a4a75b7a78c0486724470009e323aa63: 'true'
  sessionAffinity: None
  type: ClusterIP
