apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["daemonset:bf:mq-cud-facet"]'
    workload.cattle.io/targetWorkloadIdNoop: 'true'
    workload.cattle.io/workloadPortBased: 'true'
  labels:
    cattle.io/creator: norman
  name: mq-cud-facet
  namespace: bf
  ownerReferences:
  - apiVersion: apps/v1beta2
    controller: true
    kind: daemonset
    name: mq-cud-facet
    uid: adf980d3-4316-11e9-8468-fa163e4f813e
spec:
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: daemonSet-bf-mq-cud-facet
  sessionAffinity: None
  type: ClusterIP
