apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    field.cattle.io/creatorId: user-5dn6d
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: daemonSet-bf-mq-cud-search
  name: mq-cud-search
  namespace: bf
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: daemonSet-bf-mq-cud-search
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2019-04-08T16:21:42Z'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: daemonSet-bf-mq-cud-search
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: mongo
            optional: false
        - configMapRef:
            name: bf
            optional: false
        - configMapRef:
            name: log
            optional: false
        image: blueforest/mq-search:1.0.3
        imagePullPolicy: Always
        name: mq-cud-search
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /mq.json
          name: rabbit
          subPath: mq.json
        - mountPath: /queue.json
          name: queue
          subPath: queue.json
        - mountPath: /jobs.json
          name: search-jobs
          subPath: jobs.json
        - mountPath: /subjobs.json
          name: search-sub-jobs
          subPath: subjobs.json
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: hub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: rabbit
        secret:
          defaultMode: 256
          optional: false
          secretName: rabbit
      - configMap:
          defaultMode: 256
          name: queue
          optional: false
        name: queue
      - configMap:
          defaultMode: 256
          name: search-jobs
          optional: false
        name: search-jobs
      - configMap:
          defaultMode: 256
          name: search-sub-jobs
          optional: false
        name: search-sub-jobs
  templateGeneration: 2
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
