apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["daemonset:bf:mq-cud-impacttank"]'
    workload.cattle.io/targetWorkloadIdNoop: 'true'
    workload.cattle.io/workloadPortBased: 'true'
  labels:
    cattle.io/creator: norman
  name: mq-cud-impacttank
  namespace: bf
  ownerReferences:
  - apiVersion: apps/v1beta2
    controller: true
    kind: daemonset
    name: mq-cud-impacttank
    uid: f6366836-73d6-11e9-9fe8-eeeeeeeeeeee
spec:
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: daemonSet-bf-mq-cud-impacttank
  sessionAffinity: None
  type: ClusterIP
