apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    field.cattle.io/creatorId: user-5dn6d
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: daemonSet-bf-mq-cud-info
  name: mq-cud-info
  namespace: bf
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: daemonSet-bf-mq-cud-info
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2019-04-08T16:23:14Z'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: daemonSet-bf-mq-cud-info
    spec:
      containers:
      - env:
        - name: DB_COLLECTION
          value: info
        - name: NAME
          value: info
        - name: DB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              key: DB_CONNECTION_STRING
              name: mongo
              optional: false
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              key: NODE_ENV
              name: bf
              optional: false
        envFrom:
        - configMapRef:
            name: log
            optional: false
        image: blueforest/mq-upsert-delete:1.0.4
        imagePullPolicy: Always
        name: mq-cud-info
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /mq.json
          name: rabbit
          readOnly: true
          subPath: mq.json
        - mountPath: /queue.json
          name: queue
          readOnly: true
          subPath: queue.json
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: hub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: rabbit
        secret:
          defaultMode: 256
          optional: false
          secretName: rabbit
      - configMap:
          defaultMode: 256
          name: queue
          optional: false
        name: queue
  templateGeneration: 3
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
