apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["daemonset:bf:mq-impact-tank"]'
    workload.cattle.io/targetWorkloadIdNoop: 'true'
    workload.cattle.io/workloadPortBased: 'true'
  labels:
    cattle.io/creator: norman
  name: mq-impact-tank
  namespace: bf
  ownerReferences:
  - apiVersion: apps/v1beta2
    controller: true
    kind: daemonset
    name: mq-impact-tank
    uid: 12402df2-6a9e-11e9-8c04-fa163e4f813e
spec:
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: daemonSet-bf-mq-impact-tank
  sessionAffinity: None
  type: ClusterIP
