apiVersion: v1
data:
  queue.json: "{\n  \"options\": {\n    \"exclusive\": false,\n    \"durable\": false,\n\
    \    \"autoDelete\": false\n  }\n}"
kind: ConfigMap
metadata:
  annotations:
    field.cattle.io/creatorId: user-5dn6d
  labels:
    cattle.io/creator: norman
  name: queue
  namespace: bf
