apiVersion: v1
data:
  jobs.json: '["trunk", "info"]'
kind: ConfigMap
metadata:
  annotations:
    field.cattle.io/creatorId: user-5dn6d
  labels:
    cattle.io/creator: norman
  name: search-jobs
  namespace: bf
