apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    field.cattle.io/creatorId: user-5dn6d
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: daemonSet-bf-user
  name: user
  namespace: bf
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: daemonSet-bf-user
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2019-02-10T13:44:44Z'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: daemonSet-bf-user
    spec:
      containers:
      - env:
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              key: DEBUG
              name: log
              optional: false
        envFrom:
        - secretRef:
            name: mongo
            optional: false
        - secretRef:
            name: jwt
            optional: false
        - configMapRef:
            name: bf
            optional: false
        - secretRef:
            name: user
            optional: false
        image: blueforest/user:1.1.0
        imagePullPolicy: Always
        name: user
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: hub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  templateGeneration: 9
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
