apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    field.cattle.io/creatorId: user-5dn6d
    field.cattle.io/publicEndpoints: '[{"addresses":["51.77.136.161"],"port":443,"protocol":"HTTPS","serviceName":"bf:ingress-a08f5f00fc38a36b135f10009d58e0fc","ingressName":"bf:bf-ing","hostname":"blueforest.org","path":"/","allNodes":true}]'
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: daemonSet-bf-web
  name: web
  namespace: bf
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: daemonSet-bf-web
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2019-03-19T13:49:58Z'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: daemonSet-bf-web
    spec:
      containers:
      - image: blueforest/web:2.0.6
        imagePullPolicy: Always
        name: web
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: hub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  templateGeneration: 31
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
