apiVersion: v1
data:
  log-format-upstream: '{"request_id": "$req_id", "method": "$request_method", "status":$status,
    "vhost": "$host", "path": "$uri","request_query": "$args", "request_length": $request_length,
    "duration": $request_time, "bytes_sent": $bytes_sent, "request_proto": "$server_protocol",
    "http_user_agent":"$http_user_agent" }'
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: ingress-nginx
  name: nginx-configuration
  namespace: ingress-nginx
