apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations: {}
  labels:
    app: cattle-agent
  name: cattle-node-agent
  namespace: cattle-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cattle-agent
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cattle-agent
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/os
                operator: NotIn
                values:
                - windows
      containers:
      - env:
        - name: CATTLE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CATTLE_SERVER
          value: https://ranch.blueforest.org
        - name: CATTLE_CA_CHECKSUM
        - name: CATTLE_CLUSTER
          value: 'false'
        - name: CATTLE_K8S_MANAGED
          value: 'true'
        - name: CATTLE_AGENT_CONNECT
          value: 'true'
        image: rancher/rancher-agent:v2.1.3
        imagePullPolicy: IfNotPresent
        name: agent
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /cattle-credentials
          name: cattle-credentials
          readOnly: true
        - mountPath: /etc/kubernetes
          name: k8s-ssl
        - mountPath: /var/run
          name: var-run
        - mountPath: /run
          name: run
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: cattle
      serviceAccountName: cattle
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        key: node-role.kubernetes.io/etcd
        value: 'true'
      - effect: NoSchedule
        key: node-role.kubernetes.io/controlplane
        value: 'true'
      volumes:
      - hostPath:
          path: /etc/kubernetes
          type: DirectoryOrCreate
        name: k8s-ssl
      - hostPath:
          path: /var/run
          type: DirectoryOrCreate
        name: var-run
      - hostPath:
          path: /run
          type: DirectoryOrCreate
        name: run
      - name: cattle-credentials
        secret:
          defaultMode: 420
          secretName: cattle-credentials-703ae9a
  templateGeneration: 1
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
