apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  labels:
    app: cattle-cluster-agent
  name: cattle-cluster-agent
  namespace: cattle-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cattle-cluster-agent
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cattle-cluster-agent
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/os
                operator: NotIn
                values:
                - windows
      containers:
      - env:
        - name: CATTLE_SERVER
          value: https://ranch.blueforest.org
        - name: CATTLE_CA_CHECKSUM
        - name: CATTLE_CLUSTER
          value: 'true'
        - name: CATTLE_K8S_MANAGED
          value: 'true'
        image: rancher/rancher-agent:v2.1.3
        imagePullPolicy: IfNotPresent
        name: cluster-register
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /cattle-credentials
          name: cattle-credentials
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: cattle
      serviceAccountName: cattle
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cattle-credentials
        secret:
          defaultMode: 420
          secretName: cattle-credentials-703ae9a
