apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq-ha
    chart: rabbitmq-ha-1.19.0
    heritage: Tiller
    io.cattle.field/appId: rabbitmq-ha
    release: rabbitmq-ha
  name: rabbitmq-ha
  namespace: rabbitmq-ha
spec:
  ports:
  - name: http
    port: 15672
    protocol: TCP
    targetPort: http
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: amqp
  - name: epmd
    port: 4369
    protocol: TCP
    targetPort: epmd
  selector:
    app: rabbitmq-ha
    release: rabbitmq-ha
  sessionAffinity: None
  type: ClusterIP
