apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: postgres
  name: datadir-postgres-0
  namespace: kong
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
