apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  namespace: kong
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: kong-proxy
    nodePort: 31432
    port: 80
    protocol: TCP
    targetPort: 8000
  - name: kong-proxy-ssl
    nodePort: 30072
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: kong
  sessionAffinity: None
  type: LoadBalancer
