apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:imports:import"]'
    workload.cattle.io/targetWorkloadIdNoop: 'true'
    workload.cattle.io/workloadPortBased: 'true'
  labels:
    cattle.io/creator: norman
  name: import
  namespace: imports
  ownerReferences:
  - apiVersion: apps/v1beta2
    controller: true
    kind: deployment
    name: import
    uid: 4a3d3de4-02ab-11e9-8468-fa163e4f813e
spec:
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: deployment-imports-import
  sessionAffinity: None
  type: ClusterIP
