apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '5'
    field.cattle.io/creatorId: user-5dn6d
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-imports-import
  name: import
  namespace: imports
spec:
  paused: true
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-imports-import
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2018-12-20T10:54:37Z'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-imports-import
    spec:
      containers:
      - env:
        - name: DEBUG
          value: api:*
        - name: NODE_ENV
          value: production
        envFrom:
        - secretRef:
            name: mongo
        - configMapRef:
            name: user
        image: blueforest/import:1.0.23
        imagePullPolicy: Always
        name: import
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: hub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
