apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '55'
    field.cattle.io/creatorId: user-5dn6d
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-imports-off-import
  name: off-import
  namespace: imports
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-imports-off-import
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2019-05-08T13:18:59Z'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-imports-off-import
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - one
      containers:
      - env:
        - name: DEBUG
          value: api:*
        - name: IMPORT_FILTER
          value: '{}'
        - name: LOG_EVERY
          value: '5000'
        - name: NODE_ENV
          value: production
        - name: PRODUCT_PATH
          value: /dump/off/products.bson
        - name: DB_CONNECTION_STRING_OFF
          valueFrom:
            configMapKeyRef:
              key: DB_CONNECTION_STRING_OFF
              name: 'off'
              optional: false
        envFrom:
        - configMapRef:
            name: 'off'
            optional: false
        - secretRef:
            name: mongo
            optional: false
        - configMapRef:
            name: user
            optional: false
        image: blueforest/off-import:1.2.4
        imagePullPolicy: Always
        name: off-import
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /mq.json
          name: rabbit
          subPath: mq.json
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: hub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: rabbit
        secret:
          defaultMode: 256
          optional: false
          secretName: rabbit
