apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:imports:off-import"]'
    workload.cattle.io/targetWorkloadIdNoop: 'true'
    workload.cattle.io/workloadPortBased: 'true'
  labels:
    cattle.io/creator: norman
  name: off-import
  namespace: imports
  ownerReferences:
  - apiVersion: apps/v1beta2
    controller: true
    kind: deployment
    name: off-import
    uid: 07491ee9-fd5f-11e8-8468-fa163e4f813e
spec:
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: deployment-imports-off-import
  sessionAffinity: None
  type: ClusterIP
