apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '17'
    field.cattle.io/creatorId: user-5dn6d
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-imports-off-import
  name: off-import
  namespace: imports
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-imports-off-import
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2019-04-08T09:23:46Z'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-imports-off-import
    spec:
      containers:
      - env:
        - name: DEBUG
          value: api:*
        - name: IMPORT_FILTER
          value: '{}'
        - name: NODE_ENV
          value: production
        envFrom:
        - configMapRef:
            name: 'off'
        - secretRef:
            name: mongo
        - configMapRef:
            name: user
        image: blueforest/off-import:1.1.0
        imagePullPolicy: Always
        name: off-import
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /mq.json
          name: rabbit
          subPath: mq.json
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: hub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: rabbit
        secret:
          defaultMode: 256
          optional: false
          secretName: rabbit
